# Introduction
In this workbook, we will build a neural network from scratch.  You will be introduced to PyTorch and the power of neural networks.  We will be working on a synthetic dataset that catalogs the daily number of lemons sold at a lemon stand.  After training, the neural network will be ablet to predict the number of lemons that are likely going to be sold on a given day.  Lets get started!

Lets start by importing the software libraries we will need to build our neural network

In [1]:
# Import PyTorch libraries
import torch
from torch import nn 

### Check the PyTorch Version
Here we verify that PyTorch has been loaded and also the version of PyTorch.  Keep in mind, we usually want to run the latest version.  Check at the link below to verify the latest version of PyTorch:
    
    https://pytorch.org/

In [2]:
# Verify PyTorch libraries have been loaded
torch.__version__

'1.2.0'

## Import our Dataset
Neural networks need lots of data.  We will start by loading all the lemonade stand data.

The data has been collected in a table with the following columns:  'Weekend', 'Afternoon', 'Sunny', 'Warm', 'Sign', 'CuteDog', 'Ballons', 'Discount', 'FreshlyPicked', 'Ice', 'CleanHouse', 'DogWalked', 'NumberLemonsSold'

The number we want our neural network to predict is the field called 'NumberLemonsSold'!

In [4]:
import pandas as pd
df = pd.read_csv('lemons.csv', nrows=1) # just get the columns
columns = df.columns.tolist() # get the columns
print (columns)
cols_to_use = columns[:len(columns)-1] # drop the last one
xDF = pd.read_csv('lemons.csv', usecols=cols_to_use)
print (xDF.head())
yDF = pd.read_csv('lemons.csv', usecols=['NumberLemonsSold'])
print (yDF.head())

['Weekend', 'Afternoon', 'Sunny', 'Warm', 'Sign', 'CuteDog', 'Ballons', 'Discount', 'FreshlyPicked', 'Ice', 'CleanHouse', 'DogWalked', 'NumberLemonsSold']
   Weekend  Afternoon  Sunny  Warm  Sign  CuteDog  Ballons  Discount  \
0        1          1      1     0     1        0        0         0   
1        1          0      1     0     1        0        0         0   
2        0          0      1     0     0        1        1         0   
3        0          0      1     1     0        1        0         0   
4        1          1      1     0     0        1        0         0   

   FreshlyPicked  Ice  CleanHouse  DogWalked  
0              0    1           0          1  
1              0    0           1          0  
2              0    0           0          0  
3              1    1           1          1  
4              1    1           0          0  
   NumberLemonsSold
0                10
1                 7
2                 0
3                 0
4                14


In [5]:
x = torch.tensor(xDF.values,dtype=torch.float)
y = torch.tensor(yDF.values,dtype=torch.float)
print (x)
print (y)

tensor([[1., 1., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 0., 1., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 1., 1.],
        [1., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 1.]])
tensor([[10.],
        [ 7.],
        [ 0.],
        ...,
        [ 0.],
        [ 2.],
        [ 0.]])


In [6]:
class MyFirstNetwork(nn.Module):
    def __init__(self):
        super(MyFirstNetwork, self).__init__()
        self.network = nn.Sequential(
            nn.Linear(12,30),
            nn.ReLU(),
            nn.Linear(30,1)
        )
        
    def forward(self, x):
        logits = self.network(x)
        return logits

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('A {} device was found for processing'.format(device))

A cpu device was found for processing


In [8]:
model = MyFirstNetwork()

In [9]:
model.to(device)
x = x.to(device)
y = y.to(device)

In [10]:
x

tensor([[1., 1., 1.,  ..., 1., 0., 1.],
        [1., 0., 1.,  ..., 0., 1., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 1., 1.],
        [1., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 1.]])

In [11]:
import torch.optim as optim
criterion = torch.nn.MSELoss()  #reduction='sum' maybe?
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)
for epoch in range(5):
    totalLoss = 0
    for i in range(len(x)):
        # Forward pass: Compute predicted y by passing x to the model
        
        optimizer.zero_grad()
        ypred = model(x[i])
        loss = criterion(ypred, y[i])
        totalLoss+=loss.item()
        loss.backward()
        optimizer.step()
    print (totalLoss)


8882.82708154848
65.425484356639
24.194293607279025
15.966863013023694
10.566484175369105


In [12]:
# Data that affects the number of lemons sold in one day
weekend = 1
afternoon = 1
sunny = 1
warm = 0

sign = 1
cutedog = 0
ballons = 1
discount = 1
freshlypicked = 1
ice = 1

# Data that usually does not affect lemons sold
houseclean = 1
dogwentwalk = 1

numlemonssold = 0
if weekend:
    numlemonssold = afternoon + sunny*5 + warm*10 + sign*2 + cutedog + ballons+discount+freshlypicked*5 + ice*2

print ("Actual ", numlemonssold)


Actual  17


In [13]:
model.to('cpu')
x = torch.tensor([weekend, afternoon,sunny,warm, sign, cutedog, 
                 ballons, discount, freshlypicked, ice, houseclean, 
                 dogwentwalk],dtype=float)
y=model(x.float())
print("Model Predicted: ",y.item())

Model Predicted:  17.047454833984375
